In [2]:
import numpy as np

In [2]:
l1=[1,2,3,4,5,6,7,8,9,10]
l2=[]
for i in range(1,11):
    l2.append(i**2)
print(l2)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


# 1 dimensional array

In [3]:
a=np.array([12,3,4,5,6,7,8,9,10])
a

array([12,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
a= np.array(l1)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
a.ndim

1

In [8]:
a.shape

(10,)

In [9]:
len(a)

10

# 2 dimensional array:-

In [12]:
a= np.array([[1,1],[2,2]])
a

array([[1, 1],
       [2, 2]])

In [13]:
a= np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
a.ndim

2

In [15]:
a.shape

(2, 3)

In [16]:
len(a)

2

In [17]:
for i in range(1,3):
    for j in range(1,4):
        print(i,end=" ")
    print()

1 1 1 
2 2 2 


In [20]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [21]:
a.ndim

3

In [22]:
a.shape

(2, 2, 2)

In [26]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [27]:
a.shape

(3, 2, 2)

In [28]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]],[[13,14],[16,17]]])
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [16, 17]]])

In [29]:
a.shape

(4, 2, 2)

# inbuilt numpy functions

In [30]:
a=np.linspace(0,1,10)
a

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [31]:
1.0-0.88888889

0.11111110999999996

In [32]:
0.88888889-0.77777778

0.11111111000000007

In [34]:
a= np.linspace(0,100,4)
a

array([  0.        ,  33.33333333,  66.66666667, 100.        ])

In [36]:
a= np.linspace(1,100,200)
a

array([  1.        ,   1.49748744,   1.99497487,   2.49246231,
         2.98994975,   3.48743719,   3.98492462,   4.48241206,
         4.9798995 ,   5.47738693,   5.97487437,   6.47236181,
         6.96984925,   7.46733668,   7.96482412,   8.46231156,
         8.95979899,   9.45728643,   9.95477387,  10.45226131,
        10.94974874,  11.44723618,  11.94472362,  12.44221106,
        12.93969849,  13.43718593,  13.93467337,  14.4321608 ,
        14.92964824,  15.42713568,  15.92462312,  16.42211055,
        16.91959799,  17.41708543,  17.91457286,  18.4120603 ,
        18.90954774,  19.40703518,  19.90452261,  20.40201005,
        20.89949749,  21.39698492,  21.89447236,  22.3919598 ,
        22.88944724,  23.38693467,  23.88442211,  24.38190955,
        24.87939698,  25.37688442,  25.87437186,  26.3718593 ,
        26.86934673,  27.36683417,  27.86432161,  28.36180905,
        28.85929648,  29.35678392,  29.85427136,  30.35175879,
        30.84924623,  31.34673367,  31.84422111,  32.34

In [37]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
a= np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
a= np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
a= np.diag([10,20,30,40])
a

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 40]])

In [44]:
a.dtype

dtype('int32')

In [45]:
a= np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
a.dtype

dtype('float64')

In [47]:
a= np.array([1,2,3,4,5,6,7],dtype="float64")
a

array([1., 2., 3., 4., 5., 6., 7.])

In [48]:
a= np.array([1,2,3,4,5,6,7],dtype="int64")
a

array([1, 2, 3, 4, 5, 6, 7], dtype=int64)

In [49]:
a= np.array([2+3j,5+3j])
a

array([2.+3.j, 5.+3.j])

In [50]:
a.dtype

dtype('complex128')

In [51]:
a= np.array(["rashmi","ram","sham"])
a

array(['rashmi', 'ram', 'sham'], dtype='<U6')

In [52]:
a.dtype

dtype('<U6')

# Indexing and slicing

In [5]:
a=np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
print(a[4])

4


In [7]:
print(a[0:5])

[0 1 2 3 4]


In [8]:
print(a[-1])

10


In [9]:
print(a[::-1])

[10  9  8  7  6  5  4  3  2  1  0]


In [10]:
a.min()

0

In [11]:
a.max()

10

In [13]:
a=np.diag([1,2,3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [14]:
a[0,0]

1

In [15]:
a[2,2]

3

In [16]:
a[1,1]=200

In [17]:
a

array([[  1,   0,   0],
       [  0, 200,   0],
       [  0,   0,   3]])

In [19]:
a=np.arange(11,21)
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [21]:
a[::2]

array([11, 13, 15, 17, 19])

In [22]:
a=np.arange(11,21)
a
a[::3]

array([11, 14, 17, 20])

In [23]:
a[5:]=100

In [24]:
a

array([ 11,  12,  13,  14,  15, 100, 100, 100, 100, 100])

In [35]:
a=np.arange(0,10)
a
b=np.arange(0,5)
b

array([0, 1, 2, 3, 4])

In [36]:
a[5:]=b[::-1]
a


array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [37]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
b=a[::2]
b

array([0, 2, 4, 6, 8])

# Mask

In [39]:
a=np.random.randint(0,100,15)
mask=(a%2==0)
even= a[mask]
even

array([30, 10,  4, 22, 12])

In [40]:
a

array([ 9,  1, 79, 30, 10, 45, 99, 27,  4, 22, 39, 12, 71, 91, 93])

In [48]:
# a[mask]=0
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

# Advanced Indexing

In [42]:
a=np.arange(0,100)
mask=(a[::10])

In [43]:
skip=a[mask]
skip

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [46]:
a=np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [47]:
a[[2,3,2,5]]

array([20, 30, 20, 50])

# Basic arithmatic operations on numpy arrays

In [50]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
a+10

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [52]:
a+2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [53]:
a*5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [54]:
a**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [55]:
a**3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [56]:
a**5

array([     1,     32,    243,   1024,   3125,   7776,  16807,  32768,
        59049, 100000], dtype=int32)

In [60]:
a=np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [61]:
a*a

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [62]:
a.dot(a) 

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [76]:
a=np.array([1,1,0,0])
b=np.array([1,0,1,0])

In [71]:
a==b

array([False,  True, False,  True])

In [72]:
a<b

array([ True, False,  True, False])

In [73]:
a<=b

array([ True,  True,  True,  True])

In [74]:
a!=b

array([ True, False,  True, False])

In [77]:
np.logical_and(a,b)

array([ True, False, False, False])

In [78]:
np.logical_or(a,b)

array([ True,  True,  True, False])

In [79]:
a=np.arange(4)

In [80]:
b=np.arange(2)

In [81]:
a

array([0, 1, 2, 3])

In [82]:
b

array([0, 1])

In [84]:
# a+b

In [85]:
np.sum(a)

6

In [86]:
a=np.array([[1,1],[2,2]])
a

array([[1, 1],
       [2, 2]])

In [88]:
np.sum(a,axis=0)

array([3, 3])

In [89]:
np.sum(a,axis=1)

array([2, 4])

In [90]:
np.all([True,True,False])

False

In [91]:
np.any([True,True,False])

True

In [92]:
np.any([False,False,False])

False

In [93]:
np.all([False,False,False])

False

In [94]:
np.any([True,True,True])

True